# Generated by Django 6.0.2 on 2026-02-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
